### ISSUE TITLE
Synchroization Issue

### ISSUE THREAD

**Issue by halasourav** [Bluscream/GTACoop#11] opened 2016-08-19 17:43 UTC
It works brilliant when me and my friend are not quite at the same place in the map. But when nearby, we are having a lot of synchronization issues. I am sure you are aware of this situation. However, is there any solution to this. We really want to play coop bad. It's pretty amazing, if not for this error.

**Comment by Bluscream** [comment] 2016-12-03 19:20
Duplicate of #9

**Closed** 2016-12-03 19:20 UTC
Labels: duplicate
