### ISSUE TITLE
Nothing happened when select "Server Browser" on main menu !

### ISSUE THREAD

**Issue by beefpm** [Bluscream/GTACoop#34] opened 2016-10-27 07:39 UTC
When I push F9 it's worked and the main menu came out, but when I select "Server Browser" it just close and I cannot push F9 to call the main menu again. So I have to restart the game to push F9 but it still the same problem. What should I do?

Thanks.

I update all files already.

**Comment by Bluscream** [comment] 2016-12-03 19:23
Duplicate of #13

**Closed by Bluscream** 2016-12-03 19:23 UTC
Labels: duplicate
