### ISSUE TITLE
f9 Not working

### ISSUE THREAD

**Issue by viper117** [Bluscream/GTACoop#16] opened 2016-08-26 19:27 UTC
I have installed everything as directed... copied script folder in the gta v root file.,. both script hooks are installed.. idk what else to do.. please help...

**Comment by viper117** [comment] 2016-08-26 19:33
Why would have scripthookvdotnet fail to load....? please help

**Comment by soccermitchy** [comment] 2016-08-26 19:47
Duplicate of #14 (we still do not have a solution at the moment)

**Closed by soccermitchy** 2016-08-26 19:47 UTC
