### ISSUE TITLE
f9 Not working

### ISSUE THREAD

**Issue by viper117** [Bluscream/GTACoop#17] opened 2016-08-27 03:58 UTC
is this mod compatible with the non-steam version... i downloaded the game directly from rockstar

**Comment by soccermitchy** [comment] 2016-08-27 04:14
Yes, it is. Reply on the other thread I linked since I'm setting up github
to mute closed issues now.

**Comment by soccermitchy** [comment] 2016-08-27 04:15
... oh, you opened a new issue. Duplicate of #14.

**Closed by soccermitchy** 2016-08-27 04:15 UTC
