### ISSUE TITLE
"Can't handle tick"

### ISSUE THREAD

**Issue by Chazz-K** [Bluscream/GTACoop#36] opened 2016-11-11 03:35 UTC
I have Port Forwarding set up, I finally was able to get everything going, or so I thought. I had my roommate try to connect, and I got the following error:
Can't handle tick: System.NullReferenceException: Object reference not set to an instance of an object.
I have no idea what to do with this.
Screenshot here: https://i.imgur.com/TSLSZFp.jpg

**Comment by soccermitchy** [comment] 2016-11-11 03:40
Possible duplicate of #22? Either way, send me a .zip (or a link to a .zip) of your server files to b2404e573054@studiowolfree.com (note: email will no longer work in a week). Doing it this way so you don't worry about other people getting the files for your server, and I get a notification that you sent is as a bonus.

**Comment by Pvpmedics** [comment] 2016-11-25 07:24
Hi have you found a solution for this error yet. I am getting the same error in the same situation. Cant get roomate to connect

**Comment by Litceo** [comment] 2016-12-03 13:12
me too

**Closed** 2016-12-03 19:25 UTC
Labels: duplicate
